// GENERATED CODE — DO NOT EDIT BY HAND.
//
// Source: hanna_methods.yaml
// Regenerate: dart run tool/gen_hanna_methods.dart

part of 'hanna_checker.dart';

/// Every pocket-checker model the camera scan supports, in
/// display order, generated from `hanna_methods.yaml`.
const List<HannaChecker> kHannaCheckers = [
  HannaChecker(
    'HI780',
    'ph',
    unit: 'pH',
    decimals: 1,
    min: 6.3,
    max: 8.6,
    color: CheckerColor.white,
  ),
  HannaChecker(
    'HI772',
    'alkalinity',
    tag: 'dKH',
    unit: 'dKH',
    decimals: 1,
    min: 0,
    max: 20,
    color: CheckerColor.blue,
  ),
  HannaChecker(
    'HI755',
    'alkalinity',
    tag: 'ppm',
    unit: 'ppm',
    decimals: 0,
    min: 0,
    max: 300,
    factor: 0.056,
    color: CheckerColor.blue,
  ),
  HannaChecker(
    'HI784',
    'ammonia',
    unit: 'ppm',
    decimals: 2,
    min: 0,
    max: 2.5,
    color: CheckerColor.yellow,
  ),
  HannaChecker(
    'HI758',
    'calcium',
    unit: 'ppm',
    decimals: 0,
    min: 200,
    max: 600,
    color: CheckerColor.red,
  ),
  HannaChecker(
    'HI783',
    'magnesium',
    unit: 'ppm',
    decimals: 0,
    min: 1000,
    max: 1800,
    color: CheckerColor.graphite,
  ),
  HannaChecker(
    'HI781',
    'nitrate',
    tag: 'LR',
    unit: 'ppm',
    decimals: 2,
    min: 0,
    max: 5,
    color: CheckerColor.lavender,
  ),
  HannaChecker(
    'HI782',
    'nitrate',
    tag: 'HR',
    unit: 'ppm',
    decimals: 1,
    min: 0,
    max: 75,
    color: CheckerColor.lavender,
  ),
  HannaChecker(
    'HI764',
    'nitrite',
    tag: 'ULR',
    unit: 'ppb',
    decimals: 0,
    min: 0,
    max: 200,
    factor: 0.001,
    color: CheckerColor.green,
  ),
  HannaChecker(
    'HI767',
    'nitrite',
    tag: 'LR',
    unit: 'ppb',
    decimals: 0,
    min: 0,
    max: 999,
    factor: 0.001,
    color: CheckerColor.orange,
  ),
  HannaChecker(
    'HI707',
    'nitrite',
    tag: 'LR fresh',
    unit: 'ppb',
    decimals: 0,
    min: 0,
    max: 600,
    factor: 0.001,
    color: CheckerColor.red,
  ),
  HannaChecker(
    'HI774',
    'phosphate',
    tag: 'ULR',
    unit: 'ppm',
    decimals: 2,
    min: 0,
    max: 0.9,
    color: CheckerColor.green,
  ),
  HannaChecker(
    'HI713',
    'phosphate',
    tag: 'LR',
    unit: 'ppm',
    decimals: 2,
    min: 0,
    max: 2.5,
    color: CheckerColor.green,
  ),
  HannaChecker(
    'HI736',
    'phosphate',
    tag: 'P ULR',
    unit: 'ppb',
    decimals: 0,
    min: 0,
    max: 200,
    factor: 0.003066,
    color: CheckerColor.green,
  ),
];
