// GENERATED CODE — DO NOT EDIT BY HAND.
//
// Source: parameters.yaml
// Regenerate: dart run tool/gen_parameters.dart

part of 'parameter_catalog.dart';

/// The built-in catalog of typical reef aquarium parameters,
/// generated from `parameters.yaml`.
const List<ParameterDef> kReefParameters = [
  ParameterDef(
    key: 'temperature',
    unit: '°C',
    decimals: 1,
    dashboardGroup: DashboardGroup.environment,
    minValue: 0,
    plausibleMin: 10,
    plausibleMax: 40,
    importance: 3,
  ),
  ParameterDef(
    key: 'ph',
    unit: 'pH',
    decimals: 2,
    dashboardGroup: DashboardGroup.environment,
    minValue: 0,
    plausibleMin: 5,
    plausibleMax: 10,
    importance: 2.5,
  ),
  ParameterDef(
    key: 'salinity',
    unit: 'SG',
    decimals: 3,
    dashboardGroup: DashboardGroup.environment,
    minValue: 1.0,
    plausibleMin: 1.0,
    plausibleMax: 1.05,
    importance: 3,
  ),
  ParameterDef(
    key: 'alkalinity',
    unit: 'dKH',
    decimals: 1,
    dashboardGroup: DashboardGroup.core,
    minValue: 0,
    plausibleMin: 0,
    plausibleMax: 30,
    maxDailyRise: 1.4,
    importance: 3,
  ),
  ParameterDef(
    key: 'calcium',
    unit: 'ppm',
    decimals: 0,
    dashboardGroup: DashboardGroup.core,
    minValue: 0,
    plausibleMin: 100,
    plausibleMax: 1000,
    maxDailyRise: 50,
    importance: 2,
  ),
  ParameterDef(
    key: 'magnesium',
    unit: 'ppm',
    decimals: 0,
    dashboardGroup: DashboardGroup.core,
    minValue: 0,
    plausibleMin: 800,
    plausibleMax: 2000,
    maxDailyRise: 100,
    importance: 2,
  ),
  ParameterDef(
    key: 'nitrate',
    unit: 'ppm',
    decimals: 1,
    dashboardGroup: DashboardGroup.nutrients,
    minValue: 0,
    plausibleMin: 0,
    plausibleMax: 250,
    importance: 2,
  ),
  ParameterDef(
    key: 'phosphate',
    unit: 'ppm',
    decimals: 2,
    dashboardGroup: DashboardGroup.nutrients,
    minValue: 0,
    plausibleMin: 0,
    plausibleMax: 5,
    importance: 2,
  ),
  ParameterDef(
    key: 'ammonia',
    unit: 'ppm',
    decimals: 2,
    dashboardGroup: DashboardGroup.nutrients,
    minValue: 0,
    plausibleMin: 0,
    plausibleMax: 10,
    importance: 3,
  ),
  ParameterDef(
    key: 'nitrite',
    unit: 'ppb',
    decimals: 0,
    dashboardGroup: DashboardGroup.nutrients,
    displayFactor: 1000,
    minValue: 0,
    plausibleMin: 0,
    plausibleMax: 10,
    importance: 3,
  ),
  ParameterDef(
    key: 'orp',
    unit: 'mV',
    decimals: 0,
    dashboardGroup: DashboardGroup.environment,
    plausibleMin: -300,
    plausibleMax: 700,
  ),
  ParameterDef(
    key: 'strontium',
    unit: 'mg/L',
    decimals: 1,
    category: ParamCategory.trace,
    symbol: 'Sr',
    minValue: 0,
    plausibleMin: 0,
    plausibleMax: 50,
    defaultBounds: ZoneBounds(
      amberLow: 5.5,
      greenLow: 7.0,
      greenHigh: 9.5,
      amberHigh: 12.0,
    ),
    hobbyKit: true,
  ),
  ParameterDef(
    key: 'iodine',
    unit: 'mg/L',
    decimals: 3,
    category: ParamCategory.trace,
    symbol: 'I',
    minValue: 0,
    plausibleMin: 0,
    plausibleMax: 2,
    defaultBounds: ZoneBounds(
      amberLow: 0.03,
      greenLow: 0.05,
      greenHigh: 0.08,
      amberHigh: 0.12,
    ),
    hobbyKit: true,
  ),
  ParameterDef(
    key: 'iron',
    unit: 'µg/L',
    decimals: 1,
    category: ParamCategory.trace,
    symbol: 'Fe',
    displayFactor: 1000,
    minValue: 0,
    plausibleMin: 0,
    plausibleMax: 2,
    defaultBounds: ZoneBounds(greenHigh: 0.005, amberHigh: 0.015),
    hobbyKit: true,
  ),
  ParameterDef(
    key: 'sodium',
    unit: 'mg/L',
    decimals: 0,
    category: ParamCategory.major,
    symbol: 'Na',
    minValue: 0,
    plausibleMin: 3000,
    plausibleMax: 20000,
    defaultBounds: ZoneBounds(
      amberLow: 9500,
      greenLow: 10000,
      greenHigh: 11200,
      amberHigh: 12000,
    ),
  ),
  ParameterDef(
    key: 'potassium',
    unit: 'mg/L',
    decimals: 0,
    category: ParamCategory.major,
    symbol: 'K',
    minValue: 0,
    plausibleMin: 100,
    plausibleMax: 800,
    defaultBounds: ZoneBounds(
      amberLow: 340,
      greenLow: 380,
      greenHigh: 420,
      amberHigh: 460,
    ),
  ),
  ParameterDef(
    key: 'sulfur',
    unit: 'mg/L',
    decimals: 0,
    category: ParamCategory.major,
    symbol: 'S',
    minValue: 0,
    plausibleMin: 200,
    plausibleMax: 2000,
    defaultBounds: ZoneBounds(
      amberLow: 780,
      greenLow: 850,
      greenHigh: 980,
      amberHigh: 1100,
    ),
  ),
  ParameterDef(
    key: 'boron',
    unit: 'mg/L',
    decimals: 1,
    category: ParamCategory.major,
    symbol: 'B',
    minValue: 0,
    plausibleMin: 0,
    plausibleMax: 20,
    defaultBounds: ZoneBounds(
      amberLow: 3.0,
      greenLow: 3.8,
      greenHigh: 5.5,
      amberHigh: 7.0,
    ),
  ),
  ParameterDef(
    key: 'bromine',
    unit: 'mg/L',
    decimals: 0,
    category: ParamCategory.major,
    symbol: 'Br',
    minValue: 0,
    plausibleMin: 0,
    plausibleMax: 300,
    defaultBounds: ZoneBounds(
      amberLow: 45,
      greenLow: 55,
      greenHigh: 75,
      amberHigh: 95,
    ),
  ),
  ParameterDef(
    key: 'silicon',
    unit: 'mg/L',
    decimals: 2,
    category: ParamCategory.major,
    symbol: 'Si',
    minValue: 0,
    plausibleMin: 0,
    plausibleMax: 10,
    defaultBounds: ZoneBounds(greenHigh: 0.15, amberHigh: 0.5),
  ),
  ParameterDef(
    key: 'zinc',
    unit: 'µg/L',
    decimals: 1,
    category: ParamCategory.trace,
    symbol: 'Zn',
    displayFactor: 1000,
    minValue: 0,
    plausibleMin: 0,
    plausibleMax: 1,
    defaultBounds: ZoneBounds(greenHigh: 0.01, amberHigh: 0.03),
  ),
  ParameterDef(
    key: 'vanadium',
    unit: 'µg/L',
    decimals: 1,
    category: ParamCategory.trace,
    symbol: 'V',
    displayFactor: 1000,
    minValue: 0,
    plausibleMin: 0,
    plausibleMax: 1,
    defaultBounds: ZoneBounds(greenHigh: 0.003, amberHigh: 0.008),
  ),
  ParameterDef(
    key: 'copper',
    unit: 'µg/L',
    decimals: 1,
    category: ParamCategory.trace,
    symbol: 'Cu',
    displayFactor: 1000,
    minValue: 0,
    plausibleMin: 0,
    plausibleMax: 1,
    defaultBounds: ZoneBounds(greenHigh: 0.002, amberHigh: 0.01),
  ),
  ParameterDef(
    key: 'nickel',
    unit: 'µg/L',
    decimals: 1,
    category: ParamCategory.trace,
    symbol: 'Ni',
    displayFactor: 1000,
    minValue: 0,
    plausibleMin: 0,
    plausibleMax: 1,
    defaultBounds: ZoneBounds(greenHigh: 0.002, amberHigh: 0.008),
  ),
  ParameterDef(
    key: 'manganese',
    unit: 'µg/L',
    decimals: 1,
    category: ParamCategory.trace,
    symbol: 'Mn',
    displayFactor: 1000,
    minValue: 0,
    plausibleMin: 0,
    plausibleMax: 1,
    defaultBounds: ZoneBounds(greenHigh: 0.005, amberHigh: 0.02),
  ),
  ParameterDef(
    key: 'molybdenum',
    unit: 'µg/L',
    decimals: 1,
    category: ParamCategory.trace,
    symbol: 'Mo',
    displayFactor: 1000,
    minValue: 0,
    plausibleMin: 0,
    plausibleMax: 1,
    defaultBounds: ZoneBounds(
      amberLow: 0.001,
      greenLow: 0.005,
      greenHigh: 0.015,
      amberHigh: 0.03,
    ),
  ),
  ParameterDef(
    key: 'chromium',
    unit: 'µg/L',
    decimals: 2,
    category: ParamCategory.trace,
    symbol: 'Cr',
    displayFactor: 1000,
    minValue: 0,
    plausibleMin: 0,
    plausibleMax: 1,
    defaultBounds: ZoneBounds(greenHigh: 0.001, amberHigh: 0.005),
  ),
  ParameterDef(
    key: 'cobalt',
    unit: 'µg/L',
    decimals: 2,
    category: ParamCategory.trace,
    symbol: 'Co',
    displayFactor: 1000,
    minValue: 0,
    plausibleMin: 0,
    plausibleMax: 1,
    defaultBounds: ZoneBounds(greenHigh: 0.001, amberHigh: 0.004),
  ),
  ParameterDef(
    key: 'lithium',
    unit: 'µg/L',
    decimals: 0,
    category: ParamCategory.trace,
    symbol: 'Li',
    displayFactor: 1000,
    minValue: 0,
    plausibleMin: 0,
    plausibleMax: 5,
    defaultBounds: ZoneBounds(
      amberLow: 0.05,
      greenLow: 0.12,
      greenHigh: 0.25,
      amberHigh: 0.4,
    ),
  ),
  ParameterDef(
    key: 'barium',
    unit: 'µg/L',
    decimals: 1,
    category: ParamCategory.trace,
    symbol: 'Ba',
    displayFactor: 1000,
    minValue: 0,
    plausibleMin: 0,
    plausibleMax: 1,
    defaultBounds: ZoneBounds(
      amberLow: 0.001,
      greenLow: 0.004,
      greenHigh: 0.02,
      amberHigh: 0.05,
    ),
  ),
  ParameterDef(
    key: 'selenium',
    unit: 'µg/L',
    decimals: 2,
    category: ParamCategory.trace,
    symbol: 'Se',
    displayFactor: 1000,
    minValue: 0,
    plausibleMin: 0,
    plausibleMax: 1,
    defaultBounds: ZoneBounds(greenHigh: 0.005, amberHigh: 0.015),
  ),
  ParameterDef(
    key: 'aluminium',
    unit: 'µg/L',
    decimals: 1,
    category: ParamCategory.contaminant,
    symbol: 'Al',
    displayFactor: 1000,
    minValue: 0,
    plausibleMin: 0,
    plausibleMax: 2,
    defaultBounds: ZoneBounds(greenHigh: 0.01, amberHigh: 0.05),
  ),
  ParameterDef(
    key: 'antimony',
    unit: 'µg/L',
    decimals: 2,
    category: ParamCategory.contaminant,
    symbol: 'Sb',
    displayFactor: 1000,
    minValue: 0,
    plausibleMin: 0,
    plausibleMax: 1,
    defaultBounds: ZoneBounds(greenHigh: 0.002, amberHigh: 0.01),
  ),
  ParameterDef(
    key: 'tin',
    unit: 'µg/L',
    decimals: 2,
    category: ParamCategory.contaminant,
    symbol: 'Sn',
    displayFactor: 1000,
    minValue: 0,
    plausibleMin: 0,
    plausibleMax: 1,
    defaultBounds: ZoneBounds(greenHigh: 0.003, amberHigh: 0.01),
  ),
  ParameterDef(
    key: 'beryllium',
    unit: 'µg/L',
    decimals: 2,
    category: ParamCategory.contaminant,
    symbol: 'Be',
    displayFactor: 1000,
    minValue: 0,
    plausibleMin: 0,
    plausibleMax: 1,
    defaultBounds: ZoneBounds(greenHigh: 0.0005, amberHigh: 0.002),
  ),
  ParameterDef(
    key: 'silver',
    unit: 'µg/L',
    decimals: 2,
    category: ParamCategory.contaminant,
    symbol: 'Ag',
    displayFactor: 1000,
    minValue: 0,
    plausibleMin: 0,
    plausibleMax: 1,
    defaultBounds: ZoneBounds(greenHigh: 0.0005, amberHigh: 0.002),
  ),
  ParameterDef(
    key: 'tungsten',
    unit: 'µg/L',
    decimals: 2,
    category: ParamCategory.contaminant,
    symbol: 'W',
    displayFactor: 1000,
    minValue: 0,
    plausibleMin: 0,
    plausibleMax: 1,
    defaultBounds: ZoneBounds(greenHigh: 0.001, amberHigh: 0.005),
  ),
  ParameterDef(
    key: 'lanthanum',
    unit: 'µg/L',
    decimals: 2,
    category: ParamCategory.contaminant,
    symbol: 'La',
    displayFactor: 1000,
    minValue: 0,
    plausibleMin: 0,
    plausibleMax: 1,
    defaultBounds: ZoneBounds(greenHigh: 0.001, amberHigh: 0.005),
  ),
  ParameterDef(
    key: 'titanium',
    unit: 'µg/L',
    decimals: 1,
    category: ParamCategory.contaminant,
    symbol: 'Ti',
    displayFactor: 1000,
    minValue: 0,
    plausibleMin: 0,
    plausibleMax: 1,
    defaultBounds: ZoneBounds(greenHigh: 0.002, amberHigh: 0.01),
  ),
  ParameterDef(
    key: 'zirconium',
    unit: 'µg/L',
    decimals: 2,
    category: ParamCategory.contaminant,
    symbol: 'Zr',
    displayFactor: 1000,
    minValue: 0,
    plausibleMin: 0,
    plausibleMax: 1,
    defaultBounds: ZoneBounds(greenHigh: 0.001, amberHigh: 0.005),
  ),
  ParameterDef(
    key: 'arsenic',
    unit: 'µg/L',
    decimals: 1,
    category: ParamCategory.contaminant,
    symbol: 'As',
    displayFactor: 1000,
    minValue: 0,
    plausibleMin: 0,
    plausibleMax: 1,
    defaultBounds: ZoneBounds(greenHigh: 0.004, amberHigh: 0.012),
  ),
  ParameterDef(
    key: 'cadmium',
    unit: 'µg/L',
    decimals: 2,
    category: ParamCategory.contaminant,
    symbol: 'Cd',
    displayFactor: 1000,
    minValue: 0,
    plausibleMin: 0,
    plausibleMax: 1,
    defaultBounds: ZoneBounds(greenHigh: 0.0005, amberHigh: 0.002),
  ),
  ParameterDef(
    key: 'mercury',
    unit: 'µg/L',
    decimals: 2,
    category: ParamCategory.contaminant,
    symbol: 'Hg',
    displayFactor: 1000,
    minValue: 0,
    plausibleMin: 0,
    plausibleMax: 1,
    defaultBounds: ZoneBounds(greenHigh: 0.0003, amberHigh: 0.001),
  ),
  ParameterDef(
    key: 'lead',
    unit: 'µg/L',
    decimals: 1,
    category: ParamCategory.contaminant,
    symbol: 'Pb',
    displayFactor: 1000,
    minValue: 0,
    plausibleMin: 0,
    plausibleMax: 1,
    defaultBounds: ZoneBounds(greenHigh: 0.002, amberHigh: 0.008),
  ),
];
