// GENERATED CODE — DO NOT EDIT BY HAND.
//
// Source: parameters.yaml
// Regenerate: dart run tool/gen_parameters.dart

part of 'parameter_catalog.dart';

/// The built-in catalog of typical reef aquarium parameters,
/// generated from `parameters.yaml`.
const List<ParameterDef> kReefParameters = [
  ParameterDef(
    key: 'temperature',
    unit: '°C',
    decimals: 1,
    minValue: 0,
    plausibleMin: 10,
    plausibleMax: 40,
  ),
  ParameterDef(
    key: 'ph',
    unit: 'pH',
    decimals: 2,
    minValue: 0,
    plausibleMin: 5,
    plausibleMax: 10,
  ),
  ParameterDef(
    key: 'salinity',
    unit: 'SG',
    decimals: 3,
    minValue: 1.0,
    plausibleMin: 1.0,
    plausibleMax: 1.05,
  ),
  ParameterDef(
    key: 'alkalinity',
    unit: 'dKH',
    decimals: 1,
    minValue: 0,
    plausibleMin: 0,
    plausibleMax: 30,
  ),
  ParameterDef(
    key: 'calcium',
    unit: 'ppm',
    decimals: 0,
    minValue: 0,
    plausibleMin: 100,
    plausibleMax: 1000,
  ),
  ParameterDef(
    key: 'magnesium',
    unit: 'ppm',
    decimals: 0,
    minValue: 0,
    plausibleMin: 800,
    plausibleMax: 2000,
  ),
  ParameterDef(
    key: 'nitrate',
    unit: 'ppm',
    decimals: 1,
    minValue: 0,
    plausibleMin: 0,
    plausibleMax: 250,
  ),
  ParameterDef(
    key: 'phosphate',
    unit: 'ppm',
    decimals: 2,
    minValue: 0,
    plausibleMin: 0,
    plausibleMax: 5,
  ),
  ParameterDef(
    key: 'ammonia',
    unit: 'ppm',
    decimals: 2,
    minValue: 0,
    plausibleMin: 0,
    plausibleMax: 10,
  ),
  ParameterDef(
    key: 'nitrite',
    unit: 'ppm',
    decimals: 2,
    minValue: 0,
    plausibleMin: 0,
    plausibleMax: 10,
  ),
  ParameterDef(
    key: 'orp',
    unit: 'mV',
    decimals: 0,
    plausibleMin: -300,
    plausibleMax: 700,
  ),
  ParameterDef(
    key: 'potassium',
    unit: 'ppm',
    decimals: 0,
    minValue: 0,
    plausibleMin: 100,
    plausibleMax: 800,
  ),
  ParameterDef(
    key: 'strontium',
    unit: 'mg/L',
    decimals: 1,
    category: ParamCategory.trace,
    symbol: 'Sr',
    minValue: 0,
    plausibleMin: 0,
    plausibleMax: 50,
  ),
  ParameterDef(
    key: 'iodine',
    unit: 'mg/L',
    decimals: 3,
    category: ParamCategory.trace,
    symbol: 'I',
    minValue: 0,
    plausibleMin: 0,
    plausibleMax: 2,
  ),
  ParameterDef(
    key: 'iron',
    unit: 'µg/L',
    decimals: 1,
    category: ParamCategory.trace,
    symbol: 'Fe',
    displayFactor: 1000,
    minValue: 0,
    plausibleMin: 0,
    plausibleMax: 2,
  ),
  ParameterDef(
    key: 'sodium',
    unit: 'mg/L',
    decimals: 0,
    category: ParamCategory.major,
    symbol: 'Na',
    minValue: 0,
    plausibleMin: 3000,
    plausibleMax: 20000,
  ),
  ParameterDef(
    key: 'sulfur',
    unit: 'mg/L',
    decimals: 0,
    category: ParamCategory.major,
    symbol: 'S',
    minValue: 0,
    plausibleMin: 200,
    plausibleMax: 2000,
  ),
  ParameterDef(
    key: 'boron',
    unit: 'mg/L',
    decimals: 1,
    category: ParamCategory.major,
    symbol: 'B',
    minValue: 0,
    plausibleMin: 0,
    plausibleMax: 20,
  ),
  ParameterDef(
    key: 'bromine',
    unit: 'mg/L',
    decimals: 0,
    category: ParamCategory.major,
    symbol: 'Br',
    minValue: 0,
    plausibleMin: 0,
    plausibleMax: 300,
  ),
  ParameterDef(
    key: 'silicon',
    unit: 'mg/L',
    decimals: 2,
    category: ParamCategory.major,
    symbol: 'Si',
    minValue: 0,
    plausibleMin: 0,
    plausibleMax: 10,
  ),
  ParameterDef(
    key: 'zinc',
    unit: 'µg/L',
    decimals: 1,
    category: ParamCategory.trace,
    symbol: 'Zn',
    displayFactor: 1000,
    minValue: 0,
    plausibleMin: 0,
    plausibleMax: 1,
  ),
  ParameterDef(
    key: 'vanadium',
    unit: 'µg/L',
    decimals: 1,
    category: ParamCategory.trace,
    symbol: 'V',
    displayFactor: 1000,
    minValue: 0,
    plausibleMin: 0,
    plausibleMax: 1,
  ),
  ParameterDef(
    key: 'copper',
    unit: 'µg/L',
    decimals: 1,
    category: ParamCategory.trace,
    symbol: 'Cu',
    displayFactor: 1000,
    minValue: 0,
    plausibleMin: 0,
    plausibleMax: 1,
  ),
  ParameterDef(
    key: 'nickel',
    unit: 'µg/L',
    decimals: 1,
    category: ParamCategory.trace,
    symbol: 'Ni',
    displayFactor: 1000,
    minValue: 0,
    plausibleMin: 0,
    plausibleMax: 1,
  ),
  ParameterDef(
    key: 'manganese',
    unit: 'µg/L',
    decimals: 1,
    category: ParamCategory.trace,
    symbol: 'Mn',
    displayFactor: 1000,
    minValue: 0,
    plausibleMin: 0,
    plausibleMax: 1,
  ),
  ParameterDef(
    key: 'molybdenum',
    unit: 'µg/L',
    decimals: 1,
    category: ParamCategory.trace,
    symbol: 'Mo',
    displayFactor: 1000,
    minValue: 0,
    plausibleMin: 0,
    plausibleMax: 1,
  ),
  ParameterDef(
    key: 'chromium',
    unit: 'µg/L',
    decimals: 2,
    category: ParamCategory.trace,
    symbol: 'Cr',
    displayFactor: 1000,
    minValue: 0,
    plausibleMin: 0,
    plausibleMax: 1,
  ),
  ParameterDef(
    key: 'cobalt',
    unit: 'µg/L',
    decimals: 2,
    category: ParamCategory.trace,
    symbol: 'Co',
    displayFactor: 1000,
    minValue: 0,
    plausibleMin: 0,
    plausibleMax: 1,
  ),
  ParameterDef(
    key: 'lithium',
    unit: 'µg/L',
    decimals: 0,
    category: ParamCategory.trace,
    symbol: 'Li',
    displayFactor: 1000,
    minValue: 0,
    plausibleMin: 0,
    plausibleMax: 5,
  ),
  ParameterDef(
    key: 'barium',
    unit: 'µg/L',
    decimals: 1,
    category: ParamCategory.trace,
    symbol: 'Ba',
    displayFactor: 1000,
    minValue: 0,
    plausibleMin: 0,
    plausibleMax: 1,
  ),
  ParameterDef(
    key: 'selenium',
    unit: 'µg/L',
    decimals: 2,
    category: ParamCategory.trace,
    symbol: 'Se',
    displayFactor: 1000,
    minValue: 0,
    plausibleMin: 0,
    plausibleMax: 1,
  ),
  ParameterDef(
    key: 'aluminium',
    unit: 'µg/L',
    decimals: 1,
    category: ParamCategory.contaminant,
    symbol: 'Al',
    displayFactor: 1000,
    minValue: 0,
    plausibleMin: 0,
    plausibleMax: 2,
  ),
  ParameterDef(
    key: 'antimony',
    unit: 'µg/L',
    decimals: 2,
    category: ParamCategory.contaminant,
    symbol: 'Sb',
    displayFactor: 1000,
    minValue: 0,
    plausibleMin: 0,
    plausibleMax: 1,
  ),
  ParameterDef(
    key: 'tin',
    unit: 'µg/L',
    decimals: 2,
    category: ParamCategory.contaminant,
    symbol: 'Sn',
    displayFactor: 1000,
    minValue: 0,
    plausibleMin: 0,
    plausibleMax: 1,
  ),
  ParameterDef(
    key: 'beryllium',
    unit: 'µg/L',
    decimals: 2,
    category: ParamCategory.contaminant,
    symbol: 'Be',
    displayFactor: 1000,
    minValue: 0,
    plausibleMin: 0,
    plausibleMax: 1,
  ),
  ParameterDef(
    key: 'silver',
    unit: 'µg/L',
    decimals: 2,
    category: ParamCategory.contaminant,
    symbol: 'Ag',
    displayFactor: 1000,
    minValue: 0,
    plausibleMin: 0,
    plausibleMax: 1,
  ),
  ParameterDef(
    key: 'tungsten',
    unit: 'µg/L',
    decimals: 2,
    category: ParamCategory.contaminant,
    symbol: 'W',
    displayFactor: 1000,
    minValue: 0,
    plausibleMin: 0,
    plausibleMax: 1,
  ),
  ParameterDef(
    key: 'lanthanum',
    unit: 'µg/L',
    decimals: 2,
    category: ParamCategory.contaminant,
    symbol: 'La',
    displayFactor: 1000,
    minValue: 0,
    plausibleMin: 0,
    plausibleMax: 1,
  ),
  ParameterDef(
    key: 'titanium',
    unit: 'µg/L',
    decimals: 1,
    category: ParamCategory.contaminant,
    symbol: 'Ti',
    displayFactor: 1000,
    minValue: 0,
    plausibleMin: 0,
    plausibleMax: 1,
  ),
  ParameterDef(
    key: 'zirconium',
    unit: 'µg/L',
    decimals: 2,
    category: ParamCategory.contaminant,
    symbol: 'Zr',
    displayFactor: 1000,
    minValue: 0,
    plausibleMin: 0,
    plausibleMax: 1,
  ),
  ParameterDef(
    key: 'arsenic',
    unit: 'µg/L',
    decimals: 1,
    category: ParamCategory.contaminant,
    symbol: 'As',
    displayFactor: 1000,
    minValue: 0,
    plausibleMin: 0,
    plausibleMax: 1,
  ),
  ParameterDef(
    key: 'cadmium',
    unit: 'µg/L',
    decimals: 2,
    category: ParamCategory.contaminant,
    symbol: 'Cd',
    displayFactor: 1000,
    minValue: 0,
    plausibleMin: 0,
    plausibleMax: 1,
  ),
  ParameterDef(
    key: 'mercury',
    unit: 'µg/L',
    decimals: 2,
    category: ParamCategory.contaminant,
    symbol: 'Hg',
    displayFactor: 1000,
    minValue: 0,
    plausibleMin: 0,
    plausibleMax: 1,
  ),
  ParameterDef(
    key: 'lead',
    unit: 'µg/L',
    decimals: 1,
    category: ParamCategory.contaminant,
    symbol: 'Pb',
    displayFactor: 1000,
    minValue: 0,
    plausibleMin: 0,
    plausibleMax: 1,
  ),
];
