# Drop-in replacement for `flutter clean` that does NOT destroy the junctions.
# It heals the links first, then empties the junction TARGETS (the disposable
# build caches outside OneDrive) instead of deleting the links themselves.
#
#   powershell -ExecutionPolicy Bypass -File scripts\safe-clean.ps1
#
# NEVER run `flutter clean` in this repo — it deletes the junction links and the
# next build recreates them as real folders inside OneDrive (the recurring bug).

. "$PSScriptRoot\_common.ps1"

Write-Host "Safe clean (target root: $script:TargetRoot)" -ForegroundColor Cyan

# Release Gradle handles so the caches can be emptied.
& (Join-Path $script:RepoRoot 'android\gradlew.bat') --stop 2>&1 | Out-Null

# Make sure the links exist before we clear what they point at.
Repair-Junctions | Out-Null

foreach ($j in $script:Junctions) {
    $target = Join-Path $script:TargetRoot $j.Target
    if (Test-Path $target) {
        Get-ChildItem $target -Force -ErrorAction SilentlyContinue |
            Remove-Item -Recurse -Force -ErrorAction SilentlyContinue
        Write-Host "  emptied    $($j.Target)"
    }
}

# Files `flutter clean` also removes (regenerated by `flutter pub get`).
Remove-Item (Join-Path $script:RepoRoot '.flutter-plugins-dependencies') -Force -ErrorAction SilentlyContinue

Write-Host "`nClean done (junctions intact). Run 'flutter pub get' next." -ForegroundColor Cyan
